console.log("Generic search/autocomplete interview");
console.log("");
console.log("Service shape:");
console.log("- Route: GET /v1/search/suggest?q=<query>&limit=<n>");
console.log("- Current baseline: naive full scan with title-prefix matching only.");
console.log("- The repo has clear seams for query normalization, data/index prep, ranking, route behavior, and benchmarking.");
console.log("");
console.log("Fixed task:");
console.log("- Extend search so query tokens can match title, aliases, and tags.");
console.log("- Support multi-token, token-order-insensitive matching.");
console.log("- Keep the API shape coherent while improving relevance and latency.");
console.log("- Do not blindly pick an algorithm. Compare at least two approaches before you commit.");
console.log("");
console.log("Required working style:");
console.log("- Spend the first 10 minutes mapping the repo before coding.");
console.log("- Be ready to explain at least two bounded AI workstreams:");
console.log("  - one for repo tracing / call-path understanding");
console.log("  - one for algorithm comparison or ranking/index alternatives");
console.log("  - optional: one for benchmark or test design");
console.log("- By the end, add at least one correctness test and improve the benchmarking/profiling workflow so it is useful for future optimization.");
console.log("");
console.log("Next step:");
console.log("- Explain how you will understand the repo, what you will delegate, and which algorithms you want to compare.");
console.log("- Then run npm run interview:task. It prints the current behavior gaps and latency baseline.");
